area/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import AreaList, AreaCreate, AreaUpdate, AreaDelete

app_name = 'area'
urlpatterns = [
    path('list/', AreaList.as_view(), name='list'),
    path('create/',AreaCreate.as_view(), name='create'),
    path('update/<int:pk>/', AreaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', AreaDelete.as_view(), name='delete'),

]

service_desk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('empleado/', include('empleado.urls', namespace='empleado')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
    path('incidente/', include('incidente.urls', namespace='incidente')),
    path('equipo/', include('equipo.urls', namespace='equipo')),
    path('area/', include('area.urls', namespace='area')),
    path('especialidad/', include('especialidad.urls', namespace='especialidad')),

]

usuario/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import  UserList, TechnicalList, EmployeeList, UserCreate, UserUpdate, UserDelete, LoginView, LogoutView

app_name = 'usuario'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
     path('logout/', LogoutView.as_view(), name='logout'),
    path('list/', UserList.as_view(), name='list'),
    path('technical/', TechnicalList.as_view(), name='technical'),
    path('employee/', EmployeeList.as_view(), name='employee'),
    path('create/', UserCreate.as_view(), name='create'),
    path('update/<int:pk>/', UserUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', UserDelete.as_view(), name='delete'),
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager

from especialidad.models import Especialidad
from area.models    import Area
from .managers import UserManager

class User(AbstractUser):
    tipo = [
        ( 0 , 'Empleado'),
        ( 1 , 'Call-Center'),
        ( 2 , 'Tecnico')
    ]

    tipo_usuario = models.SmallIntegerField(choices=tipo, null=True, blank=True)

    especialidad = models.ForeignKey(Especialidad,on_delete = models.CASCADE, null = True)
    area = models.ForeignKey(Area, on_delete = models.CASCADE, blank=True, null=True)

    tipos = UserManager()
    objects = BaseUserManager()

    def __str__(self):
        return self.first_name

usuario/forms.py
import re
from django.forms import ModelForm
from.models import User

class UserForm(ModelForm):

    fields_required = [
        'first_name', 'last_name',
        'email'

    ]
    
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'first_name',
            'last_name',
            'email',
            'especialidad',
            'tipo_usuario'
        ]

        labels = {
            'especialidad': 'Especialidad'
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

usuario/views.py
from django.shortcuts import render
from django.views.generic import ListView ,CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User
from .forms import UserForm

# Create your views here.
class UserList(LoginRequiredMixin, ListView):
    model = User
    template_name = "usuario/index.html"

class TechnicalList(LoginRequiredMixin, ListView):
    model = User
    template_name = "usuario/index.html"
    queryset = User.tipos.tecnicos()

class EmployeeList(LoginRequiredMixin, ListView):
    model = User
    template_name = "usuario/index.html"
    queryset = User.tipos.empleados()

class UserCreate(LoginRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('usuario:list')
    template_name = 'usuario/form.html'

class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('usuario:list')
    template_name = 'usuario/update.html'

class UserDelete(LoginRequiredMixin, DeleteView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('usuario:list')
    template_name = 'usuario/delete.html'

class LoginView(auth_views.LoginView):
    redirect_authenticated_user = True

class LogoutView(auth_views.LogoutView):
    pass

templates/usuario/delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="content-wrapper">
    <br>
    <div class="central_container_form">
        <h1 class="text-center">Eliminar el técnico:</h1>
        <br><br>
        <ul class="list-group list-group-flush">
                <li class="list-group-item">Nombre de usuario: {{ object.username }}</li>
                <li class="list-group-item">Nombre: {{ object.first_name }}</li>
                <li class="list-group-item">Apellido: {{ object.last_name }}</li>
                <li class="list-group-item">Correo electronico: {{ object.email }}</li>
                <li class="list-group-item">Especialidad:</li>
        </ul>

        <form action="{% url 'usuario:delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="modal-footer">
                <button class="btn btn-danger" type="submit">Eliminar</button>               
                <a href="{% url 'usuario:list' %}" class="btn btn-secondary">Cancelar</a>                
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/usuario/form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br>
    <form class="central_container_form needs-validation was-validated" action="{% url 'usuario:create' %}" method="POST">
        <h1 class="text-center">Agregar usuario</h1><br><br>
        {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <!--<a id= "directuser" class="fas fa-fw fa-plus-circle" href="{% url 'especialidad:create' %}"></a>-->
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
            <a href="#" class="btn btn-secondary">Cancelar</a>
            <!--<a class="btn btn-primary" href="Login.html">Agregar</a>-->
        </div>
    </form>
</div>
{% endblock content %}

templates/usuario/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br>
    {% url 'usuario:technical' as technical_list %}
    {% url 'usuario:employee' as employee_list %}

    <h1 class="text-center">{% if request.path == technical_list %}Técnicos {% elif request.path == employee_list %}
        Empleados{% endif %}</h1>
    <div id="accordion" class="accordion central_container_accordion">
        <br><br>
        {% for usuario in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ usuario.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ usuario.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ usuario.id }}">
                    {{ usuario.first_name}} {{usuario.last_name}}
                </h5>
            </div>

            <div id="collapse-{{ usuario.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ usuario.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nombre de usuario: {{ usuario.username }}</li>
                    <li class="list-group-item">Nombre: {{ usuario.first_name }}</li>
                    <li class="list-group-item">Apellido: {{ usuario.last_name }}</li>
                    <li class="list-group-item">Correo electronico: {{ usuario.email }}</li>
                    <li class="list-group-item">Admistrador: {{ usuario.especialidad }}</li>
                </ul>
                <div class="text-right">
                    <div class="card-body">
                        <a href="{% url 'usuario:update' usuario.id %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'usuario:delete' usuario.id %}" class="btn btn-danger">Eliminar</a>
                    </div>
                </div>

            </div>
        </div>
        {% empty %}
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">No se han encontrado datos.</h1>
                <p class="lead">Verifique con el administrador tener tecnicos registrados.</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/usuario/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br>
    <form class="central_container_form needs-validation was-validatedx"
        action="{% url 'usuario:update' object.id %}" method="POST">
        <h1 class="text-center">Modificar técnico <a class="fas fa-fw fa-list-ul" href="{% url 'usuario:list' %}"></a></h1>
        <br><br>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Guardar</button>
            <a href="{% url 'usuario:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}