area/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import AreaList, AreaCreate, AreaUpdate, AreaDelete

app_name = 'area'
urlpatterns = [
    path('list/', AreaList.as_view(), name='list'),
    path('create/',AreaCreate.as_view(), name='create'),
    path('update/<int:pk>/', AreaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', AreaDelete.as_view(), name='delete'),

]

incidente/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import (IncidenteList ,IncidenteCreate,IncidenteDelete,IncidenteUpdate,
                    Estadisticas, IncidenteTechnicalList, IncidenteFinish, IncidenteFinishedList,
                    IncidenteFinishedTechnicalList, EstadisticasFechas, EstadisticasEmpleado)

app_name = 'incidente'
urlpatterns = [
    path('list/', IncidenteList.as_view(), name='list'),
    path('my-list/', IncidenteTechnicalList.as_view(), name='my-list'),
    path('finished/', IncidenteFinishedList.as_view(), name='list-finished'),
    path('myfinished/', IncidenteFinishedTechnicalList.as_view(), name='my-list-finished'),
    path('stats/', Estadisticas.as_view(), name='stats'),
    path('stats/fecha/', EstadisticasFechas.as_view(), name='stats-fecha'),
    path('stats/empleados/', EstadisticasEmpleado.as_view(), name='stats-empleado'),
    path('create/', IncidenteCreate.as_view(), name='create'),
    path('update/<int:pk>/', IncidenteUpdate.as_view(), name='update'),
    path('finish/<int:pk>/', IncidenteFinish.as_view(), name='finish'),
    path('delete/<int:pk>/', IncidenteDelete.as_view(), name='delete'),
]

service_desk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('empleado/', include('empleado.urls', namespace='empleado')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
    path('incidente/', include('incidente.urls', namespace='incidente')),
    path('equipo/', include('equipo.urls', namespace='equipo')),
    path('area/', include('area.urls', namespace='area')),
    path('especialidad/', include('especialidad.urls', namespace='especialidad')),

]

incidente/models.py
from django.db import models

from django.conf import settings

from equipo.models import Equipo
from especialidad.models import Especialidad
from django.db.models import Manager

from .managers import IncidenteManager


class Incidente(models.Model):
    RANGO = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    nombre = models.CharField(max_length=50)
    descripcion_del_empleado = models.TextField(null=True)
    descripcion_del_tecnico = models.TextField(null=True)
    estado = models.BooleanField()
    prioridad = models.IntegerField(choices=RANGO, default=1)
    fecha_inicio = models.DateTimeField(auto_now=False, auto_now_add=True)
    ultima_modificacion = models.DateTimeField(auto_now=True, auto_now_add=False)

    solucion = models.TextField(null=True, blank=True)

    empleado = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='empleados'
    )

    tecnico = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='tecnicos',
        blank=True,
        null=True
    )

    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    tipo_problema = models.ForeignKey(Especialidad, on_delete=models.CASCADE, blank=True, null=True)

    estados = IncidenteManager()
    objects = Manager()

    class Meta:
        ordering = ('fecha_inicio',)

    def __str__(self):
        return self.nombre

    def mostrar_estado(self):
        if self.estado:
            mostrar_estado = "No Solucionado"
        else:
            mostrar_estado = "solucionado"
        return mostrar_estado

    def finalizar(self):
        if self.estado:
            self.estado = False
            self.save(update_fields=['estado'])


#hola mundo

incidente/forms.py
import re
from django.forms import ModelForm, HiddenInput
from .models import Incidente
from django.contrib.auth import get_user_model

Usuario = get_user_model()

class IncidenteForm(ModelForm):

    fields_required = [
        'tipo_problema',
        'tecnico',
    ]

    class Meta:
        model = Incidente

        fields = '__all__'

        exclude = ('solucion',)


    def __init__(self, *args, **kwargs):
        super(IncidenteForm, self).__init__(*args, **kwargs)

        self.fields['tipo_problema'].required = True
        self.fields['tecnico'].required = True

        self.fields['tecnico'].queryset = Usuario.tipos.tecnicos()
        self.fields['empleado'].queryset = Usuario.tipos.empleados()

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

class IncidenteFinishForm(ModelForm):
    class Meta:
        model = Incidente
        fields = ('estado',)

incidente/views.py
import json
import datetime
import random
from itertools import groupby
from collections import OrderedDict
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView ,CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy

from django.db.models import Count, F
from django.db.models.functions import TruncMonth
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Incidente
from .forms import IncidenteForm, IncidenteFinishForm
from django.contrib.auth import get_user_model


Usuario = get_user_model()

class IncidenteList(LoginRequiredMixin, ListView):
    model = Incidente
    template_name = "incidente/index.html"
    queryset = Incidente.estados.valids()

class IncidenteTechnicalList( IncidenteList):
    def get_queryset(self):
        qs = super().get_queryset().filter(tecnico=self.request.user.id)
        return qs

class IncidenteCreate(LoginRequiredMixin, CreateView):
    model = Incidente
    form_class = IncidenteForm
    success_url = reverse_lazy('incidente:list')
    template_name = 'incidente/form.html'


class IncidenteUpdate(LoginRequiredMixin, UpdateView):
    model = Incidente
    form_class = IncidenteForm
    success_url = reverse_lazy('incidente:list')
    template_name = 'incidente/update.html'


class IncidenteDelete(LoginRequiredMixin, DeleteView):
    model = Incidente
    form_class = IncidenteForm
    success_url = reverse_lazy('incidente:list')
    template_name = 'incidente/delete.html'


class Estadisticas(LoginRequiredMixin, TemplateView):
    template_name = 'incidente/estadisticas.html'


class EstadisticasFechas(TemplateView):
    template_name = 'incidente/estadisticas_stast.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        months = list(datetime.date(2019, i, 1).strftime('%B') for i in range(1, 13))

        incidents_per_mouth = list(Incidente.objects.annotate(
            month=TruncMonth('fecha_inicio')).values('month').annotate(
            incidents=Count('id')).values('month', 'incidents'))

        datagroup = OrderedDict((k, {k1: sum(list(i['incidents'] for i in v)) for k1, v in groupby(values, key=lambda x: x['month'].strftime("%B"))}) for k, values in groupby(incidents_per_mouth, key=lambda x: x['month'].year))

        datasets = []
        for year, datamonths in datagroup.items():
            color = self.colors()
            datasets.append({
                'label': '{}'.format(year),
                'fill': False,
                'lineTension': 0,
                'backgroundColor': 'rgb({0}, {1}, {2})'.format(*color),
                'borderColor': 'rgb({0}, {1}, {2})'.format(*color),
                'data': tuple(datamonths.get(value, 0) for value in months)
            })

        data = {
            'labels': months,
            'datasets': datasets
        }

        context.update(datasets_incidents=json.dumps(data))
        return context

    def colors(self):
        r = int(random.random() * 256)
        g = int(random.random() * 256)
        b = int(random.random() * 256)

        return r, g, b

class IncidenteFinishedList(LoginRequiredMixin, ListView):
    model = Incidente
    template_name = "incidente/index.html"
    queryset = Incidente.estados.finisheds()

class IncidenteFinishedTechnicalList(LoginRequiredMixin, ListView):
    model = Incidente
    template_name = "incidente/index.html"
    queryset = Incidente.estados.finisheds()
    
    def get_queryset(self):
        qs = super().get_queryset().filter(tecnico=self.request.user.id)
        return qs


class IncidenteFinish(LoginRequiredMixin, UpdateView):
    model = Incidente
    form_class = IncidenteFinishForm
    success_url = reverse_lazy('incidente:list-finished')
    template_name = 'incidente/update.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.finalizar()
        form = self.get_form()
        return self.form_valid(form)

class EstadisticasEmpleado(TemplateView):
    template_name = 'incidente/estadisticas_doughnut.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        incidents_per_empleado = list(
            Incidente.objects.order_by('empleado__username').annotate(user=F('empleado__username')).values(
                'user').annotate(
                incidents=Count('id')).values('user', 'incidents'))

        datagroup = OrderedDict((item['user'], item['incidents']) for item in incidents_per_empleado)

        empleados = datagroup.keys()

        datasets = [{
            'data': list(datagroup.values())
        }]

        data = {
            'labels': list(empleados),
            'datasets': datasets
        }

        context.update(datasets_incidents=json.dumps(data))
        return context

    def colors(self):
        r = int(random.random() * 256)
        g = int(random.random() * 256)
        b = int(random.random() * 256)

        return r, g, b

templates/incidente/delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="content-wrapper">
    <br><br><br>
    <div class="central_container_form">
        <h1 class="text-center">Eliminar incidente:</h1>
        <br><br><br>
        <ul class="list-group list-group-flush">
                <li class="list-group-item">Nombre del incidente: {{ object.nombre }}</li>
                <li class="list-group-item">Numero de prioridad: {{ object.prioridad }}</li>
                <li class="list-group-item">Fecha de inicio: {{ object.fecha_inicio }}</li>
                <li class="list-group-item">Fecha de fin: {{ object.fecha_fin }}</li>
                <li class="list-group-item">Descripcion: {{ object.descripcion }}</li>
                <li class="list-group-item">Nombre del empleado: {{ object.empleado }}</li>
                <li class="list-group-item">Equipo: {{ object.equipo }}</li>
                
                
        </ul>
        <form action="{% url 'incidente:delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="modal-footer">
                <button class="btn btn-danger" type="submit">Eliminar</button>               
                <a href="{% url 'incidente:list' %}" class="btn btn-secondary">Cancelar</a>                
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/incidente/estadisticas.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="central_container_accordion">
        {% block stasts_title %}
        {% endblock stasts_title %}
        <div id="content-wrapper">
            {% block navstast %}
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'incidente:stats-fecha' %}">Estadisticas por fecha</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'incidente:stats-empleado' %}">Estadisticas por empleado</a>
                    </li>
                </ul>
            {% endblock navstast %}
            {% block stasts %}
            {% endblock stasts %}
        </div>
    </div>
{% endblock content %}


{% block styles %}
    {{ block.super }}
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock js %}

templates/incidente/estadisticas_doughnut.html
{% extends "incidente/estadisticas.html" %}
{% load static %}

{% block stasts %}
    <canvas id="myChart"></canvas>
{% endblock stasts %}


{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <script>
    var data = {{datasets_incidents|safe}}
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'doughnut',

        // The data for our dataset
        data: data,

        // Configuration options go here
        options: {}
    });
    </script>
{% endblock js %}

{% block stasts_title %}
<br>
<h1 class="text-center">Incidencias registradas por usuario</h1>
<br>
{% endblock stasts_title %}

templates/incidente/estadisticas_stast.html
{% extends "incidente/estadisticas.html" %}
{% load static %}

{% block stasts %}
    <canvas id="myChart"></canvas>
{% endblock stasts %}


{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <script>
    var data = {{datasets_incidents|safe}}
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: data,

        // Configuration options go here
        options: {}
    });
    </script>
{% endblock js %}

{% block stasts_title %}
<br>
<h1 class="text-center">Incidencias registradas por meses en cada año</h1>
<br>
{% endblock stasts_title %}

templates/incidente/form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br><br>
    <form class="central_container_form needs-validation was-validated" action="{% url 'incidente:create' %}"
        method="POST">
        <h1 class="text-center">Agregar incidente <a class="fas fa-fw fa-list-ul" href="{% url 'incidente:list' %}"></a>
        </h1><br><br>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}

        <div class="form-group">
            <p>Nombre del empleado:
                <!--<a id= "directuser" class="fas fa-fw fa-plus-circle" href="{% url 'usuario:create' %}"></a>-->
            </p>
            {{form.empleado}}
        </div>

        <div class="form-group">
            <p>Nombre del equipo: <!--<a id="directuser" class="fas fa-fw fa-plus-circle"
                    href="{% url 'equipo:create' %}"></a>--></p>
            {{form.equipo}}
        </div>

        <div class="form-group">
            <p>Nombre del incidente:</p>
            {{form.nombre}}
        </div>

        <div class="form-group">
            <p>Descripción del empleado:</p>
            {{form.descripcion_del_empleado}}
        </div>

        <div class="form-group">
            <p>Descripción del tecnico:</p>
            {{form.descripcion_del_tecnico}}
        </div>

        <fieldset class="border p-2">
            <legend class="w-auto">Asignar Técnico</legend>
            <div class="input-group">
                <div class="input-group-prepend">
                    <div type="checkbox" class="input-group-text">
                        {{form.estado}}
                    </div>
                </div>
                <p class="form-control" aria-label="Text input with radio button">Solucionado</p>
            </div>
            <div id="panel">
                <br>
                <div class="form-group" class="is-invalid">
                    <p>Tipo de problema:</p>
                    {{form.tipo_problema}}
                </div>

                <div class="form-group" required>
                    <p>Técnico: <!--<a id="directuser" class="fas fa-fw fa-plus-circle"
                            href="{% url 'usuario:create' %}"></a>--></p>
                    {{form.tecnico}}
                </div>

                <div class="form-group" required>
                    <p>Prioridad:</p>
                    {{form.prioridad}}
                </div>
            </div>
        </fieldset>
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
            <a href="#" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
<script>
    (function (document) {
        let id_estado = document.getElementById('id_estado')
        let panel = document.getElementById('panel')

        id_estado.addEventListener('change', (event) => {
            if (event.target.checked) {
                panel.style.display = "none"
            } else {
                panel.style.display = "block"
            }
        })
    })(document)
</script>
{% endblock content %}

templates/incidente/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br>
    <h1 class="text-center">Incidentes {% if not request.user.tipo_usuario == 2 %}<a class="fas fa-fw fa-plus-circle"
            href="{% url 'incidente:create' %}"></a>{% endif %}
    </h1>
    <div id="accordion" class="accordion central_container_accordion">
        <br><br>
        {% for incidente in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ incidente.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ incidente.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ incidente.id }}">
                    {{ incidente.nombre }} - {{ incidente.fecha_inicio }}
                </h5>
            </div>

            <div id="collapse-{{ incidente.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ incidente.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Fecha: {{ incidente.fecha_inicio }}</li>
                    <li class="list-group-item">Nombre del empleado: {{ incidente.empleado }}</li>
                    <li class="list-group-item">Equipo: {{ incidente.equipo }}</li>
                    <li class="list-group-item">Nombre del tecnico: {{ incidente.tecnico }}</li>
                    <li class="list-group-item">Nombre del incidente: {{ incidente.nombre }}</li>
                    <li class="list-group-item">Descripcion del empleado: {{ incidente.descripcion_del_empleado }}</li>
                    <li class="list-group-item">Descripcion del técnico: {{ incidente.descripcion_del_tecnico }}</li>
                    <li class="list-group-item">Estado: {{ incidente.mostrar_estado }}</li>
                    <li class="list-group-item">Numero de prioridad: {{ incidente.prioridad }}</li>
                </ul>
                {% url 'incidente:list-finished' as url_incidente %}
                <div class="text-right">
                    <div class="card-body">
                        {% if not url_incidente == request.path %}
                        <a href="#FinalizarModal-{{ incidente.id }}" class="btn btn-success"
                            data-toggle="modal">Finalizar</a>
                        {% if not request.user.tipo_usuario == 2 %}
                        <a href="{% url 'incidente:update' incidente.id %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'incidente:delete' incidente.id %}" class="btn btn-danger">Eliminar</a>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
        <div class="modal fade" id="FinalizarModal-{{ incidente.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Finalizar el contrato: {{ incidente.nombre }}
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Fecha: {{ incidente.fecha_inicio }}</li>
                            <li class="list-group-item">Nombre del empleado: {{ incidente.empleado }}</li>
                            <li class="list-group-item">Equipo: {{ incidente.equipo }}</li>
                            <li class="list-group-item">Nombre del tecnico: {{ incidente.tecnico }}</li>
                            <li class="list-group-item">Nombre del incidente: {{ incidente.nombre }}</li>
                            <!--<li class="list-group-item">Descripcion del empleado: {{ incidente.descripcion_del_empleado }}</li>
                            <li class="list-group-item">Descripcion del técnico: {{ incidente.descripcion_del_tecnico }}</li>-->
                            <li class="list-group-item">Estado: {{ incidente.mostrar_estado }}</li>
                            <li class="list-group-item">Numero de prioridad: {{ incidente.prioridad }}</li>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <form action="{% url 'incidente:finish' incidente.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="estado" value="false">
                            <button type="submit" class="btn btn-primary">Aceptar</button>
                        </form>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">No se han encontrado datos.</h1>
                <p class="lead">Verifique con el administrador o el call-center tener incidentes creados.</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/incidente/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    br<br><br>
    <form class="central_container_form needs-validation was-validatedx"
        action="{% url 'incidente:update' object.id %}" method="POST">
        <h1 class="text-center">Modificar incidente <a class="fas fa-fw fa-list-ul" href="{% url 'incidente:list' %}"></a></h1><br><br><br>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        {% endfor %}
        {{form.empleado}}
        <br>
        {{form.equipo}}
        <br>
        {{form.nombre}}
        <br>
        {{form.descripcion_del_empleado}}
        <br>
        {{form.descripcion_del_tecnico}}
        {{form.estado}}
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Guardar</button>
            <a href="{% url 'incidente:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}