area/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import AreaList, AreaCreate, AreaUpdate, AreaDelete

app_name = 'area'
urlpatterns = [
    path('list/', AreaList.as_view(), name='list'),
    path('create/',AreaCreate.as_view(), name='create'),
    path('update/<int:pk>/', AreaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', AreaDelete.as_view(), name='delete'),

]

equipo/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import EquipoList, EquipoCreate, EquipoUpdate,EquipoDelete

app_name = 'equipo'
urlpatterns = [
    path('list/', EquipoList.as_view(), name='list'),
    path('create/', EquipoCreate.as_view(), name='create'),
    path('update/<int:pk>/', EquipoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', EquipoDelete.as_view(), name='delete'),
]

service_desk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('empleado/', include('empleado.urls', namespace='empleado')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
    path('incidente/', include('incidente.urls', namespace='incidente')),
    path('equipo/', include('equipo.urls', namespace='equipo')),
    path('area/', include('area.urls', namespace='area')),
    path('especialidad/', include('especialidad.urls', namespace='especialidad')),

]

equipo/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
# Create your models here.

class Equipo (models.Model):
    garantia = [
        ('6 meses', '6 meses'),
        ('1 año', '1 año'),
        ('2 años', '2 años'),
        ('No tiene garantía', 'No tiene garantía')
    ]


    nombre = models.CharField(max_length=15)
    serial = models.IntegerField(unique=True)
    procesador = models.CharField(max_length=15)
    ram = models.CharField(max_length=60)
    placa_base = models.CharField(max_length=60)
    sistema_operativo = models.CharField(max_length=60)
    garantia = models.CharField(max_length = 30, choices=garantia)

    empleado = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.nombre

equipo/forms.py
import re
from django.forms import ModelForm
from .models import Equipo

class EquipoForm(ModelForm):
    
    class Meta:
        model = Equipo
        fields = '__all__'          
        

    def __init__(self, *args, **kwargs):
        super(EquipoForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})

equipo/views.py
from django.shortcuts import render
from django.views.generic import ListView ,CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Equipo
from .forms import EquipoForm

# Create your views here.
class EquipoList(LoginRequiredMixin, ListView):
    model = Equipo
    template_name = "equipo/index.html"

class EquipoCreate(LoginRequiredMixin, CreateView):
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('equipo:list')
    template_name = 'equipo/create.html'


class EquipoUpdate(LoginRequiredMixin, UpdateView):
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('equipo:list')
    template_name = 'equipo/update.html'

class EquipoDelete(LoginRequiredMixin, DeleteView):
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('equipo:list')
    template_name = 'equipo/delete.html'

templates/equipo/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br><br>
    <form class="central_container_form needs-validation was-validated" action="{% url 'equipo:create' %}" method="POST">
            <h1 class="text-center">Agregar equipo <a class="fas fa-fw fa-list-ul" href="{% url 'equipo:list' %}"></a></h1><br><br>
        {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <!--<a id= "directuser" class="fas fa-fw fa-plus-circle" href="{% url 'usuario:create' %}"></a>-->
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Agregar</button>
            <a href="#" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}

templates/equipo/delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="content-wrapper">
    <br><br><br>
    <div class="central_container_form">
        <h1 class="text-center">Eliminar equipo:</h1>
        <br><br><br>
        <ul class="list-group list-group-flush">
                <li class="list-group-item">Nombre de equipo: {{ equipo.nombre }}</li>
                <li class="list-group-item">Serial: {{ equipo.serial }}</li>
                <li class="list-group-item">Procesador: {{ equipo.procesador }}</li>
                <li class="list-group-item">Ram: {{ equipo.ram }}</li>
                <li class="list-group-item">Placa base: {{ equipo.placa_base }}</li>
                <li class="list-group-item">Sistema operativo: {{ equipo.sistema_operativo }}</li>
                <li class="list-group-item">Garantía: {{ equipo.garantia }}</li>
                <li class="list-group-item">Empleado responsable: {{ equipo.empleado }}</li>
                <li class="list-group-item">Area: {{ equipo.empleado.area }}</li>
                
                
        </ul>
        <form action="{% url 'equipo:delete' object.id %}" method="post">
            {% csrf_token %}
            <div class="modal-footer">
                <button class="btn btn-danger" type="submit">Eliminar</button>               
                <a href="{% url 'equipo:list' %}" class="btn btn-secondary">Cancelar</a>                
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/equipo/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    <br><br>
    <h1 class="text-center">Equipo <a class="fas fa-fw fa-plus-circle" href="{% url 'equipo:create' %}"></a></h1>
    <div id="accordion" class="accordion central_container_accordion">
        <br><br>
        {% for equipo in object_list %}
        <div class="card">
            <div class="card-header" id="heading-{{ equipo.id }}">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapse-{{ equipo.id }}" aria-expanded="true"
                    aria-controls="collapse-{{ equipo.id }}">
                    {{ equipo.nombre}}
                </h5>
            </div>

            <div id="collapse-{{ equipo.id }}" class="collapse {% if forloop.first %}show{% endif %}"
                aria-labelledby="heading-{{ equipo.id }}" data-parent="#accordion">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nombre de equipo: {{ equipo.nombre }}</li>
                    <li class="list-group-item">Serial: {{ equipo.serial }}</li>
                    <li class="list-group-item">Procesador: {{ equipo.procesador }}</li>
                    <li class="list-group-item">Ram: {{ equipo.ram }}</li>
                    <li class="list-group-item">Placa base: {{ equipo.placa_base }}</li>
                    <li class="list-group-item">Sistema operativo: {{ equipo.sistema_operativo }}</li>
                    <li class="list-group-item">Garantía: {{ equipo.garantia }}</li>
                    <li class="list-group-item">Empleado responsable: {{ equipo.empleado }}</li>
                    <li class="list-group-item">Area: {{ equipo.empleado.area }}</li>

                </ul>
                <div class="text-right">
                    <div class="card-body">
                        <a href="{% url 'equipo:update' equipo.id%} " class="btn btn-primary">Modificar</a>
                        <a href="{% url 'equipo:delete' equipo.id%}" class="btn btn-danger">Eliminar</a>
                    </div>
                </div>

            </div>
        </div>
        {% empty %}
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">No se han encontrado datos.</h1>
                <p class="lead">Verifique con el administrador tener equipos registrados.</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/equipo/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content-wrapper">
    br<br><br>
    <form class="central_container_form needs-validation was-validatedx"
        action="{% url 'equipo:update' object.id %}" method="POST">
        <h1 class="text-center">Modificar equipo <a class="fas fa-fw fa-list-ul" href="{% url 'equipo:list' %}"></a></h1><br><br><br>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="modal-footer">
            <button id="IdAgregar" class="btn btn-primary" type="submit">Guardar</button>
            <a href="{% url 'equipo:list' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>
{% endblock content %}