area/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import AreaList, AreaCreate, AreaUpdate, AreaDelete

app_name = 'area'
urlpatterns = [
    path('list/', AreaList.as_view(), name='list'),
    path('create/',AreaCreate.as_view(), name='create'),
    path('update/<int:pk>/', AreaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', AreaDelete.as_view(), name='delete'),

]

incidente/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import (IncidenteList ,IncidenteCreate,IncidenteDelete,IncidenteUpdate,
                    Estadisticas, IncidenteTechnicalList, IncidenteFinish, IncidenteFinishedList,
                    IncidenteFinishedTechnicalList, EstadisticasFechas, EstadisticasEmpleado)

app_name = 'incidente'
urlpatterns = [
    path('list/', IncidenteList.as_view(), name='list'),
    path('my-list/', IncidenteTechnicalList.as_view(), name='my-list'),
    path('finished/', IncidenteFinishedList.as_view(), name='list-finished'),
    path('myfinished/', IncidenteFinishedTechnicalList.as_view(), name='my-list-finished'),
    path('stats/', Estadisticas.as_view(), name='stats'),
    path('stats/fecha/', EstadisticasFechas.as_view(), name='stats-fecha'),
    path('stats/empleados/', EstadisticasEmpleado.as_view(), name='stats-empleado'),
    path('create/', IncidenteCreate.as_view(), name='create'),
    path('update/<int:pk>/', IncidenteUpdate.as_view(), name='update'),
    path('finish/<int:pk>/', IncidenteFinish.as_view(), name='finish'),
    path('delete/<int:pk>/', IncidenteDelete.as_view(), name='delete'),
]

service_desk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('empleado/', include('empleado.urls', namespace='empleado')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
    path('incidente/', include('incidente.urls', namespace='incidente')),
    path('equipo/', include('equipo.urls', namespace='equipo')),
    path('area/', include('area.urls', namespace='area')),
    path('especialidad/', include('especialidad.urls', namespace='especialidad')),

]

usuario/urls.py
from django.urls import path
from django.views.generic import CreateView
from .views import  UserList, TechnicalList, EmployeeList, UserCreate, UserUpdate, UserDelete, LoginView, LogoutView

app_name = 'usuario'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
     path('logout/', LogoutView.as_view(), name='logout'),
    path('list/', UserList.as_view(), name='list'),
    path('technical/', TechnicalList.as_view(), name='technical'),
    path('employee/', EmployeeList.as_view(), name='employee'),
    path('create/', UserCreate.as_view(), name='create'),
    path('update/<int:pk>/', UserUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', UserDelete.as_view(), name='delete'),
]

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Services 2.0 RBS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <!--<a class="nav-item nav-link active" href="#">Inicio</a>-->

            {% if request.user.tipo_usuario == 2 %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Incidentes
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'incidente:my-list' %}">Mis incidentes</a>
                    <a class="dropdown-item" href="{% url 'incidente:my-list-finished' %}">Mis incidentes finalizados</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Incidentes
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'incidente:list' %}">todos los incidentes</a>
                        <a class="dropdown-item" href="{% url 'incidente:list-finished' %}">todos los incidentes finalizados</a>
                    </div>
                </li>
            {% endif %}

            {% if request.user.is_staff %}
            <a class="nav-item nav-link" href="{% url 'usuario:technical' %}">Técnicos</a>
            <a class="nav-item nav-link" href="{% url 'usuario:employee' %}">Empleados</a>
            <a class="nav-item nav-link" href="{% url 'equipo:list' %}">Equipos</a>
            <a class="nav-item nav-link" href="{% url 'especialidad:list' %}">Especialidades</a>
            <a class="nav-item nav-link" href="{% url 'area:list' %}">Áreas</a>
            <a class="nav-item nav-link" href="{% url 'usuario:create' %}">Agregar un usuario</a>
            <a class="nav-item nav-link" href="{% url 'incidente:stats' %}">Estadisticas</a>
            {% endif %}
        </div>
    </div>
    <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Cerrar sesión</a>
                </div>
            </li>
        </ul>
    </nav>
    
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Cerrar Sesión</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">¿Está seguro de cerrar sesión?, para confirmar presione el botón Salir.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="{% url 'usuario:logout' %}">Salir</a>
                </div>
            </div>
        </div>
    </div>
    
</nav>